modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="staminaaddon"
version="${file.jarVersion}"
displayName="Immersive Stamina Hunger Addon"
authors="Developer"
description='''
Аддон, связывающий уровень сытости, долг стамины и отображение обводки GUI.
'''

[[dependencies.staminaaddon]]
    modId="forge"
    mandatory=true
    versionRange="[47.4.20,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.staminaaddon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
