modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="staminaaddon"
version="1.0-SNAPSHOT"
displayName="Stamina Addon"
authors="YourName"
description='''
Аддон для Immersive Stamina, исправляющий механику голода и динамический предел регенерации.
'''

[[dependencies.staminaaddon]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.staminaaddon]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

# Обязательная инструкция для загрузки миксинов Forge-модом
[mixins]
config="staminaaddon.mixins.json"
